# Build and push functions image to container registry
# This pipeline currently exists because there is no current support for GitHub integration triggers straight from a Release pipeline, so we're using an artifact trigger instead

trigger: [master, prod]
pr: none

variables:
    vmImageName: "ubuntu-latest"

stages:
    - stage: Build
      displayName: Create Artifact
      jobs:
          - job: Build
            displayName: Create Artifact
            pool:
                vmImage: $(vmImageName)
            steps:
                - task: PublishBuildArtifacts@1
                  displayName: Publish Artifacts
                  inputs:
                      PathtoPublish: '$(Build.SourcesDirectory)'
                      ArtifactName: '$(Build.BuildId)'
                      publishLocation: 'FilePath'
                      TargetPath: '.'