# Build and push functions image to container registry

trigger: [master, prod]
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'sandbox_cr'
    repository: 'swotfx'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
  displayName: 'Build and push functions image'
