# Build and push functions image to container registry

trigger: [master, prod]
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'sandbox_cr'
    repository: 'swotfx'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
  displayName: 'Build and push functions image'

- task: Docker@2
  inputs:
    containerRegistry: 'sandbox_cr'
    repository: 'serverann'
    command: 'buildAndPush'
    Dockerfile: 'containers/ann/Dockerfile'
    tags: 'latest'
  displayName: 'Build and push ANN image'

- task: Docker@2
  inputs:
    containerRegistry: 'sandbox_cr'
    repository: 'servereo'
    command: 'buildAndPush'
    Dockerfile: 'containers/eo/Dockerfile'
    tags: 'latest'
  displayName: 'Build and push EO image'
